version: "3.8"
services:
  airflow:
    build: .
    image: airflow-image
    container_name: gemstone_prediction_airflow
    ports:
      - "8080:8080"    # Expose Airflow web UI
      - "7071:7071"    # Expose MLflow server
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:7071  # Add the MLflow URI


      