services:
  airflow:
    build: 
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflow-image
    container_name: gemstone_prediction_airflow
    ports:
      - "8080:8080"    # Expose Airflow web UI
      - "7071:7071"    # Expose MLflow server
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:7071  # Add the MLflow URI
                       # Persist Airflow logs

  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flask-app-image
    container_name: gemstone_prediction_flask
    ports:
      - "8012:8012"    # Expose Flask app
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app                                 # Mount Flask app directory to container
  
  lambda:
    build:
      context: ./
      dockerfile: Dockerfile.flask  # Dockerfile for Lambda
    image: lambda-app-image
    container_name: gemstone_prediction_lambda
    ports:
      - "9000:8080"  # Expose Lambda runtime emulator for local testing
    environment:
      - AWS_LAMBDA_RUNTIME_API=http://localhost:9000
    entrypoint: ["/usr/local/bin/aws-lambda-rie"]
    command: ["app.lambda_handler"]

      